code-of-conduct.md
There should be a way to report issues in regards to the code of conduct. It's great that we currently have a code of conduct that we expect our community to follow but we need a way to report issues.
=> Add section on enforcing the code of conduct

code-of-conduct.md
Update to http://contributor-covenant.org/version/1/4/ which is the latest version. This included nicer language around enforcement and is what the original code of conduct was based on.
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Update code of conduct to the latest version

proposals/tools.md
Signed-off-by: Rob Dolin <robdolin@microsoft.com>
=> Create runtime-tools and image-tools projects

proposals/digest.md
=> fixup! Respond to comments from OCI TDC

proposals/digest.md
For record keeping, add project proposal for go-digest:
https://github.com/opencontainers/tob/issues/21
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add OCI digest project proposal

proposals/image-format/README.md, proposals/tools.md
At some point this changed from `/governance/` to `/about/`.  @caniszczyk just [updated the charter link][1], so the `/about/` version is probably canonical.
[1]: http://ircbot.wl.linuxfoundation.org/eavesdrop/%23opencontainers/%23opencontainers.2017-02-06.log.html#t2017-02-06T17:48:07
=> proposals: Update links to the scope table

README.md, proposals/selinux.md
Closes #27 
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add draft go-selinux project proposal

README.md
Fix a missing comma from 63dd0523 (#3).
=> README: Fix “2.c 6.h” → “2.c, 6.h”

proposals/distribution.md
Docker's use of `Bearer` [requires information beyond what's covered in RFC 6749 and 6750][1].  So folks writing a client that will interact with a Docker registry that uses that auth approach will need a “Docker registry's `Bearer` additions” spec to follow.  While I prefer off-the-shelf RFCs for HTTP auth, the Docker registry additions are small enough, and widely used.  ~~This change adds the client side of their specification to the new distribution-spec project. [Lots more about which parts of the auth scope would need to be in scope to cover the vanilla vs. Docker-flavored `Bearer` distinction].~~
Based on [this comment][2], I've pivoted to not including auth in the distribution scope at all.
[1]: https://github.com/xiekeyang/oci-discovery/pull/64#issue-291807003
[2]: …
=> distribution: Add in-scope and out-of-scope wording

proposals/distribution.md
There's precendent in the scope table for “Not currently being worked” (the [“Creating Reference spec for optional DNS based naming & distribution” entry][1]), but “Work not yet started” (from the [“Archival Format” entry][1]) is a more complete fragment.
The “… provide a standardized way to use DNS…” line is part of the “Creating a reference spec for optional DNS based naming and discovery” entry, so I'm dropping it from the “Specifying authentication and authorization schemes” entry.
I've dropped one of the “parallel” instances for from the parallel-naming/discovery sentence.  No need to say that twice in once sentence.
cc @caniszczyk.
[1]: https://www.opencontainers.org/about/oci-scope-table
=> distribution: Copy-edits for the scope table

proposals/distribution.md
@mikebrow and I have had [a lengthy discussion][0] before realizing that we were [not interpreting these terms the same way][1].  This commit replaces some explicit object-type lists with “objects defined in the image specification”, which is more concrete than using terms without local definitions.  I've also added image-spec links where I do use object-type terms.  And I've used the wordy but more explicit “groups of image indexes” instead of “repositories” in most cases.
I've also explicitly listed `/v2/_catalog` as out of scope.  It's a higher-level endpoint than the image-spec objects.  As [Patrick][2] and [Stephen][3] pointed out when the endpoint landed, it's for internal administration.  Matt [suggested keeping it out of the user-facing API on those grounds][4], and while that …
=> distribution: Reword scope table to avoid repository/image distinction

proposals/distribution.md
@stevvooe [points out][1] that the response code list was missing 403 and that the line is fairly low-level.  I agree with @dmcgowan [that][2] that the RFC 7235 reference is sufficient to express the idea, and the less we say, the less likely we are to be wrong ;).
[1]: https://github.com/opencontainers/tob/pull/35#discussion_r172687857
[2]: https://github.com/opencontainers/tob/pull/35#discussion_r172702752
=> distribution: Remove IANA auth-scheme sentence

proposals/distribution.md
We only need blame views when the Markdown does not provide a specific-enough anchor, and this is a link to the whole file.
Fixes the issue raised be @stevvooe [here][1].
[1]: https://github.com/opencontainers/tob/pull/35#discussion_r172689573
=> distribution: Change from blame to rendered URI for image-index

proposals/distribution.md
Tag listing should mention the endpoints and external methods relying on content addressability.
Image repositories should not be referred to as indexes, but rather as image repositories.
=> Clean up language around tag listing and repository naming

README.md, proposals/distribution.md
based off initial discussion here: https://docs.google.com/document/d/15y0SBrrDFIEM7pnU-Oe3Y6pq-eTZfo0mk-k33cS2hR4/edit#
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add distribution spec project proposal

README.md
There's no need to use absolute links for these.  And using relative links sets a good example for future proposals, because the links will work in the proposal branch's README before the referenced proposal lands in the TOB master.
There's a similar absolute link for the code-of-conduct in the distribution proposal.  The intention may have been to show the absolute URL which would be included in new project's repository.  I don't think that matters, because the project template has included a similar link since opencontainers/project-template@ee72bc89 (opencontainers/project-template#45), so I've left that alone here.
=> README: Use relative links to the proposals

proposals/artifacts.md
based on discussion during the [OCI Call on July 17, 2019]( https://hackmd.io/El8Dd2xrTlCaCG59ns5cwg#July-17-2019) and feedback on [Artifact registry support #65](https://github.com/opencontainers/distribution-spec/pull/65/#issuecomment-510944746), proposing a new repository for `artifacts`
Signed-off-by: stevenlasker@hotmail.com
=> Add artifacts proposal

CHARTER.md
The OCI scope table as an artifact when the OCI was bootstrapped as an organization. The scope of the OCI has expanded over time to include image and distribution specifications. At the end of the day, the TOB controls the overall technical scope of the organization which is fairly well defined in the charter already as "The Open Container Initiative provides an open source technical community within which industry participants may easily contribute to building a vendor-neutral, portable and open specifications and runtime that deliver on the promise of containers as a source of application portability backed by a certification program."
Signed-off-by: Chris Aniszczyk <caniszczyk@linuxfoundation.org>
=> Update charter to remove scope table

CHARTER.md
Based on feedback from @samuelkarp 
Signed-off-by: Chris Aniszczyk <caniszczyk@linuxfoundation.org>
=> Simplify mission of OCI

CHARTER.md
This doesn't contain any text changes, it only changes the layout so
that you can effectively read the charter in a terminal. I know it is
"bad practice" in the OCI to have hard line-wrapping (the argument being
that it is harder to review changes), but I've never found that to be an
issue.
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
=> CHARTER: word-wrap at 80 characters

README.md, proposals/umoci.md
This is long-awaited "merge `umoci` into OCI" proposal, which has been 
discussed in various calls and mailing list threads since the project's 
inception in 2016.
**Vote Total (Closes 2020-06-12)** (please make sure you also leave an LGTM comment):
/cc @opencontainers/tob @opencontainers/image-tools-maintainers @tych0
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
=> projects: add umoci proposal

README.md
The governance link points to a broken link; and the correct link on the
opencontainers.org page just points back to the CHARTER.md in this repo.
Let's just link to that directly.
Signed-off-by: Tycho Andersen <tycho@tycho.pizza>
=> README: fix governance link

CHARTER.md, WG-INFO.md, WG-TEMPLATE.md
(cc @caniszczyk)
This is a revised version of the OCI Working Group Draft Proposal for consideration by the TOB.
I've reworked the draft proposal somewhat, moving some details (such as lists of specific info that the TOB would require for review) into a separate `WG-INFO.md` document. That way those pieces of information could be modified by the TOB in its discretion, without requiring a subsequent formal charter amendment.
I've also made some proposed edits to the language of what remains in the charter portion, I'd encourage folks to please review closely. A minor note, I've also shifted the Working Group content into section 6(p) rather than as a new section 7, to avoid having to do lots of renumbering for the rest of the charter.
Finally, I'm including a `WG-TEMPLATE.md` document …
=> CHARTER: Add WG proposal and templates

proposals/wg-reference-types.md
Per discussion on the [November 18, 2021 OCI weekly call](https://hackmd.io/El8Dd2xrTlCaCG59ns5cwg?view#November-18-2021), feedback from @dmcgowan was to convert the issue to a proposal. @vbatts, @estesp and others on the call agreed.
PR contents copied from Issue #96
The issue is open for voting by the [OCI TOB members](https://github.com/opencontainers/tob#members), through Midnight December 1, 2021.
Voting will be tallied at the December 2nd, 2021 OCI Weekly call.
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>
=> Proposal: working group for reference types

WG-INFO.md, proposals/wg-auth.md
Signed-off-by: Brandon Mitchell <git@bmitch.net>
This PR proposes a new working group to specify authentication and authorization between registries and clients.
References:
- Existing docker specification on bearer auth: https://docs.docker.com/registry/spec/auth/token/
- Distribution spec issue: https://github.com/opencontainers/distribution-spec/issues/240
- Distribution spec issue: https://github.com/opencontainers/distribution-spec/issues/338
- OCI meeting at CloudNativeCon where the need for a working group was discussed: https://hackmd.io/nZzK_4AfRz-xgya6KkqseA
=> Working group proposal for auth

WG-INFO.md, WG-TEMPLATE.md
Signed-off-by: Brandon Mitchell <git@bmitch.net>
The reference types working group delivered their PRs. This documents that, and updates the template with some missing sections.
=> Reference types has finished, template update

WG-INFO.md, proposals/wg-image-compatibility.md
This PR proposes a new working group to create image compatibility specification.
References:
* [Revisit container and host OS compatibility](https://docs.google.com/document/d/1lzwh8DGMu5vXXHwJmnewYIMffkcOEvH8owX4UYjRcw0/edit)
* [OCI image compatibility presentation](https://docs.google.com/presentation/d/1F9GnCm2sULuyTJ5BEFZlL8Qjab81DK7g9Oy6qBfe5Qs/edit?usp=sharing)
=> Working group proposal for image compatibility

proposals/wg-freebsd-runtime.md
With two working OCI runtimes for FreeBSD ([runj](https://github.com/samuelkarp/runj), [ocijail](https://github.com/dfr/ocijail)) and several container engines including containerd, podman and cri-o, there is a need to define a FreeBSD-specific section of the runtime-spec to allow support for platform features such as resource limits and fine-grained jail permissions. This will help to ensure runtime compatibility and build a consensus for the best way to support FreeBSD container runtimes.
=> Proposal: working group for FreeBSD runtime

proposals/cgroups.md
This adds a proposal to split github.com/opencontainers/runc/libcontainer/cgroups packages to a new home at github.com/opencontainers/cgroups, which appeared as a result of discussion at https://github.com/kubernetes/kubernetes/issues/128157 (and https://github.com/kubernetes/kubernetes/issues/128157#issuecomment-2427394891 in particular).
Below is a copy-paste of the current draft.
----
Having a common cgroups management implementation in OCI for use in and outside
of runc will ensure long lasting security and interoperability throughout the
container ecosystem.
Refactor and move cgroups packages out of runc into a separate project:
https://github.com/opencontainers/runc/tree/master/libcontainer/cgroups
The new project would live in the opencontainers github organization: …
=> Add a cgroup repo/project proposal

EMERITUS.md, README.md
- Election is documented at https://github.com/opencontainers/tob/issues/145.
- Members were sorted alphabetical by last name.
- Emeritus updated to only show end date since many people served for much more than 2 years.
Fixes #145.
=> Update TOB for 2025 election
